name: sean_teleop
root: ~/sim_ws
# Hold top left trigger button (1) to enable control
windows:
  - teleop:
      layout: tiled
      panes:
        - teleop:
          - rosrun teleop_twist_keyboard teleop_twist_keyboard.py cmd_vel:=/mobile_base_controller/cmd_vel
          # - roslaunch teleop_twist_joy teleop.launch joy_config:=xbox joy_dev:=/dev/input/js0
        - relay:
          - rosrun topic_tools relay /cmd_vel /mobile_base_controller/cmd_vel
        - rosbridge:
          - roslaunch --wait rosbridge_server rosbridge_websocket.launch
        - core:
          - roscore
        - bridge:
          - roslaunch --wait social_sim_ros sim_tcp_bridge.launch
        - move_base:
          - roslaunch --wait social_sim_ros kuri_move_base_global_only.launch
        - description:
          - roslaunch --wait social_sim_ros kuri_description.launch
        - map_publisher:
          - rosrun social_sim_ros map_publisher.py
        - scan:
          - roslaunch --wait social_sim_ros depth_to_laserscan.launch
        - rviz:
          - rosrun rviz rviz -d $(rospack find social_sim_ros)/config/move.rviz
