name: semantic-tool
root: .

windows:
  - sfm:
      layout: tiled
      panes:
        - shell:
        - rosbridge:
          - roslaunch --wait rosbridge_server rosbridge_websocket.launch
        - pc_seg:
          - roslaunch --wait tvss_nav pointcloud_seg.launch