name: semantic-tool
root: .

windows:
  - sfm:
      layout: tiled
      panes:
        - shell:
        - rosbridge:
          - roslaunch --wait rosbridge_server rosbridge_websocket.launch
        - pc_seg:
          - roslaunch --wait pointcloud_seg pointcloud_seg.launch
        - costmap:
          - cd ../../tvss_nav/scripts/tvss_nav/utils/ && /usr/bin/python3.8 cloud2costmap.py